/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalentPartnerRouteImport } from './routes/talent-partner'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrepinstaRouteImport } from './routes/prepinsta'
import { Route as OnlineUniversityRouteImport } from './routes/online-university'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as GtecFranchiseRouteImport } from './routes/gtec-franchise'
import { Route as GlobalCampusRouteImport } from './routes/global-campus'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as Career247RouteImport } from './routes/career247'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TalentPartnerRoute = TalentPartnerRouteImport.update({
  id: '/talent-partner',
  path: '/talent-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepinstaRoute = PrepinstaRouteImport.update({
  id: '/prepinsta',
  path: '/prepinsta',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineUniversityRoute = OnlineUniversityRouteImport.update({
  id: '/online-university',
  path: '/online-university',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const GtecFranchiseRoute = GtecFranchiseRouteImport.update({
  id: '/gtec-franchise',
  path: '/gtec-franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalCampusRoute = GlobalCampusRouteImport.update({
  id: '/global-campus',
  path: '/global-campus',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const Career247Route = Career247RouteImport.update({
  id: '/career247',
  path: '/career247',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career247': typeof Career247Route
  '/contact': typeof ContactRoute
  '/global-campus': typeof GlobalCampusRoute
  '/gtec-franchise': typeof GtecFranchiseRoute
  '/insurance': typeof InsuranceRoute
  '/online-university': typeof OnlineUniversityRoute
  '/prepinsta': typeof PrepinstaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent-partner': typeof TalentPartnerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career247': typeof Career247Route
  '/contact': typeof ContactRoute
  '/global-campus': typeof GlobalCampusRoute
  '/gtec-franchise': typeof GtecFranchiseRoute
  '/insurance': typeof InsuranceRoute
  '/online-university': typeof OnlineUniversityRoute
  '/prepinsta': typeof PrepinstaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent-partner': typeof TalentPartnerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career247': typeof Career247Route
  '/contact': typeof ContactRoute
  '/global-campus': typeof GlobalCampusRoute
  '/gtec-franchise': typeof GtecFranchiseRoute
  '/insurance': typeof InsuranceRoute
  '/online-university': typeof OnlineUniversityRoute
  '/prepinsta': typeof PrepinstaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent-partner': typeof TalentPartnerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/career247'
    | '/contact'
    | '/global-campus'
    | '/gtec-franchise'
    | '/insurance'
    | '/online-university'
    | '/prepinsta'
    | '/sitemap.xml'
    | '/talent-partner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/career247'
    | '/contact'
    | '/global-campus'
    | '/gtec-franchise'
    | '/insurance'
    | '/online-university'
    | '/prepinsta'
    | '/sitemap.xml'
    | '/talent-partner'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/career247'
    | '/contact'
    | '/global-campus'
    | '/gtec-franchise'
    | '/insurance'
    | '/online-university'
    | '/prepinsta'
    | '/sitemap.xml'
    | '/talent-partner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  Career247Route: typeof Career247Route
  ContactRoute: typeof ContactRoute
  GlobalCampusRoute: typeof GlobalCampusRoute
  GtecFranchiseRoute: typeof GtecFranchiseRoute
  InsuranceRoute: typeof InsuranceRoute
  OnlineUniversityRoute: typeof OnlineUniversityRoute
  PrepinstaRoute: typeof PrepinstaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TalentPartnerRoute: typeof TalentPartnerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talent-partner': {
      id: '/talent-partner'
      path: '/talent-partner'
      fullPath: '/talent-partner'
      preLoaderRoute: typeof TalentPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepinsta': {
      id: '/prepinsta'
      path: '/prepinsta'
      fullPath: '/prepinsta'
      preLoaderRoute: typeof PrepinstaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-university': {
      id: '/online-university'
      path: '/online-university'
      fullPath: '/online-university'
      preLoaderRoute: typeof OnlineUniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gtec-franchise': {
      id: '/gtec-franchise'
      path: '/gtec-franchise'
      fullPath: '/gtec-franchise'
      preLoaderRoute: typeof GtecFranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-campus': {
      id: '/global-campus'
      path: '/global-campus'
      fullPath: '/global-campus'
      preLoaderRoute: typeof GlobalCampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career247': {
      id: '/career247'
      path: '/career247'
      fullPath: '/career247'
      preLoaderRoute: typeof Career247RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  Career247Route: Career247Route,
  ContactRoute: ContactRoute,
  GlobalCampusRoute: GlobalCampusRoute,
  GtecFranchiseRoute: GtecFranchiseRoute,
  InsuranceRoute: InsuranceRoute,
  OnlineUniversityRoute: OnlineUniversityRoute,
  PrepinstaRoute: PrepinstaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TalentPartnerRoute: TalentPartnerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
